module.exports={
    usercollection:'userdetails',
    vendorcollection:'vendordetails',
    admincollection:'admin',
    products:'products',
    cart:'cart',
    orders:'orders',
    banners:'banners',
    wishlist:'wishlist',
    brands:'brands',
    categories:'categories',
    coupons:'coupons',
    offers:'offers'
    }